### ISSUE TITLE
How can I save current target list used in image planner or Humanson?

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#11]
If I have a target list of say 50 targets in IM or Humanson for say the Month of Dec and Jan, I want to save this list and load it next year at same time. I find myself constantly, deleting and adding targets to the list as each month passes and will have to repeat the search next year again from scratch. If I can save the targets each month for instance I can reload them next year when that month comes up...

Maybe, the target list is stored somewhere which might even be easier if editable or being able to copy and rename file as well.

Thanks
Dale

**Comment by rrskybox** [comment]
Target imaging definitions are stored in the Humason directory in the form <targetname>.TargetPlan.xml.  If you want to archive a bunch of plans, just move one or more of those xml files into some other directory of your choice.  When you want to add targets, just move (or copy) one or more of those xml files out of that directory (or directories) into the Humason directory.  Note that Default.TargetPlan.xml retains your preferred settings for the creation of new targets so it's a good idea to leave that alone, unless you feel like swapping in different defaults.  

An example from my Humason directory (.../Documents/Humason) below.

![image](https://github.com/rrskybox/ImagePlanner/assets/40242027/8decfeec-a52b-4d40-9968-5eec32ece6c6)

**Comment by astromiester1** [comment]
Yeah, I ended up just making sub directories called Dec targets, Jan Targets etc and copy them in as appropriate. I suppose, If I delete the targets in the main directory and copy the sub in then re scan or restart should just load them in...

Thanks
Dale
