### ISSUE TITLE
Image planner general behavior with Nightshift targets.

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#13]
Curious... For some reason image planner cycles trough old targets in list before displaying the one of interest when selection via nightshift. Ie. If I have highlight IC 4517 in nightshift target list and hit  image planner launch, M1 and Abell 31 come up first from prior views before IC 4517 comes up... Would be nice once image planner is up and you double click on a target in list, image planner auto updates instead of closing current image planner and hitting image planner button again anyway... Just a thought... Thanks Dale

**Comment by rrskybox** [comment]
Not a bad idea.  Give me a few days to look into it. Thanks.

**Comment by astromiester1** [comment]
Cool beans...Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 5/5/24  9:21 PM  (GMT-05:00) To: rrskybox/ImagePlanner ***@***.***> Cc: astromiester1 ***@***.***>, Author ***@***.***> Subject: Re: [rrskybox/ImagePlanner] Image planner general behavior with Nightshift targets. (Issue #13) 
Not a bad idea.  Give me a few days to look into it. Thanks.

**Comment by rrskybox** [comment]
New versions of NightShift (Build32) and ImagePlanner (Build 104) have been posted.  NightShift now supports multiple target groups that can be saved and loaded from the Target tab.   Selection of a target from the Target tab followed by clicking on "Image Planner" will also open an instance of ImagePlanner intialized to that target.  Multiple instances of Image Planner allow the simultaneous consideration of multiple targets (but beware, simultaneous modifications to the same target could cause issues).

Image Planner will now initialize with 1) current target in NightShift (or Humason), 2) first target file in Humason directory, 3) selected target in TSX or object M1, in that order as present.  Also, if the Target field is blank when Access is checked, Image Planner will load whatever object is currently selected in the TSX Find window.

Please post any problems found with these new features or their associated uploads.  Thanks.
