### ISSUE TITLE
1st item in target list non accessible

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#15]
I notice the first item when double clicked in list for IP does not refresh the IP graph. Other targets work. If you sort on a colm and new target list appears, the 1st item still can not be accessed on graph.

**Comment by rrskybox** [comment]
My bad.  Fixed in Build 114.

**Comment by rrskybox** [comment]
Copied Target Group functionality from NightShift.  Build 115.

**Comment by astromiester1** [comment]
Everything works and looks well Rick...I added same stuff to ip as before that I had in NS. Let me know if ya want the link again. Nothing you havent seen...One thing curious about..Is it possible prospect can find targets for a lat lon, min  elevation angle and time window say dawn to dusk via TSX? I made my own list but wanted to compare to what tsx finds...ThanksDaleSent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 5/21/24  2:09 PM  (GMT-05:00) To: rrskybox/ImagePlanner ***@***.***> Cc: astromiester1 ***@***.***>, Author ***@***.***> Subject: Re: [rrskybox/ImagePlanner] 1st item in target list non accessible (Issue #15) 
Copied Target Group functionality from NightShift.  Build 115.

**Comment by rrskybox** [comment]
Prospect generates a list of objects that are visible between dusk and dawn on the month and day selected from the current location.  The list is not culled for Minimum Altitude.   Upon launch, the user selects the class of target to search for (galaxies, clusters, nebula).  TSX then runs an Observing List for that class of target and the output object list is downloaded.  The user then selects (double click) on the sub-type of object to be displayed from a list of object types found by TSX.  The resultant table displays the object name, object size, duration (visible above a minimum altitude) and maximum altitude (while visible).  The object table can be sorted alphabetically or numerically by double clicking on any of the headers.   The minimum values for size, duration and minimum maximum altitude are also computed and displayed for culling the object list.  Changing any minimum will reduce the list to only those objects with values above that minimum. 
 
A target can be selected by double clicking on any object name.  At the time, the monthly calendar and any open pop-up windows will be updated to show information about that target for the year and the selected day.  If the user selects a different day from the calendar, however, the Prospect window will be closed as its data is no longer valid for the new date.  Clicking on the Prospects button when the pop-up is open will also close the window.

The Prospect is configured for a standard set of core TSX databases: M, NGC, IC, PLN, Hershel, Cauldwell, if enabled in TSX.

The Prospect Observing List Queries can be customized in TSX if desired.  They are found in the Software Bisque "Database Queries" folder:  ImagePlannerGalaxies.dbq, ImagePlannerClusters.dbq, ImagePlannerNebula.dbq.  To modify, open Manage Observing List, load the respective query, modify and save.   For instance, if a user wants to set a minimum altitude for selected galaxy objects, the ImagePlannerGalaxies.dbg query is loaded, the Altitude attribute modified, and the query is saved back to the original.  In theory, any attribute can be modified for any of the three queries in this way.  Unfortunately, TSX observing list queries cannot be customized programmatically.

**Comment by astromiester1** [comment]
Nice explanation of your work for Prospect in planner tool… You may want to update your help file for Planner tool on last two paragraphs.

 

Thanks

Dale
