### ISSUE TITLE
Image Planner defauts to 2am in SKYX for Targets

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#16]
My time in SKYX is 7:55PM but when I launch Image planner my targets are displayed as if its 2AM and SKYX time moves to 2AM... Another way to see the same problem is if TSX shows current time and you select any cell or the cell that equals todays observation in IP, SKYX time changes to 2AM. To add more context, any cell in IP on front page where the months and days are for a specfic time. All cells no matter what time or day produce a 2AM time on SKYX in addition to a target list refresh.

**Comment by rrskybox** [comment]
Debugging this is taking a bit longer than I anticipated.  None of the code depended on maintaining the TSX Time of Day prior to the Target List function was added so I'm finding some subtle collateral damage that I've got to deal with.  No matter, just give me a few days or so.

**Comment by rrskybox** [comment]
Build 116:  Completed modifications to retain initial date and time of day post TSX interface operations.  Could still be some residual collateral damage -- just let me know.

**Comment by astromiester1** [comment]
So far so good....
