### ISSUE TITLE
Improvement Thoughts

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#4]
In TSX, I can go into the Objserving lists tab for Whats up and select general objects for the night. Not bad.. Manually, I can go into the manage Obervation lists and prepare an advanced query that looks for target for a specific FOV using Major Axis term say greater than 30am for instance for specific times during the night. Your Quick pick is similar with slide bars. Kind of cool bye the way. Anyway, did you ever think to add the same or similar functionality to image planner? Again, if your slammed, I might look into this and let ya know how it goes. It might be useful as I have 3 scopes each night I have to scramble to figure out the best targets to go after.

Thanks
Dale

**Comment by rrskybox** [comment]
Image Planner does something pretty close.  Click on "Prospect", then pick an object type that you might be interested in -- galaxies, nebula or cluster.  Lastly double click on the sub-category of object.  This function runs a TSX observing list query as you describe.   In the middle column of the Prospect window, adjust the minimum object size,  altitude and duration.  This will cull the list further.  

      Double click on an object it will load it into the calendar showing visibility information for each date.
      Click on "Altitude" to get a graph of the altitude of the object over its imaging range.
      Click on "Track" to get a projection of the object path in conjunction with the moon's path for that date.
      Click on "Preview" to bring up an image of the object bracketed by your current FOV.
      Click on "Details" to get the objects spec's.

You can leave these windows open for subsequent object selections from the Prospect list.
