### ISSUE TITLE
Search hangs program..."Searching be patient" Using Prospect Button

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#6]
Tried using Prospect button with just galaxies 20 am, alt 75 and duration 2 hours and message "Searching be patient" stays up for hours and never returns any objects.

**Comment by rrskybox** [comment]
The first thing to look for is whether TSX is completing the given observing list query.  One problem is that TSX is an absolute compute-hog.  Make sure that the update rate for the Star Chart is set to 1 (second) in Advanced Settings.  Also try minimizing TSX -- this helps as well.  And, when you run Prospect, just click on "Galaxies", do not set any other field until you get your first type list.  When you set another field it queues up yet another search so you could be running three or four searches in succession without ever coming up for air -- especially if TSX is consuming all the bandwidth updating its star chart.

If none of that changes anything, then just try running the query directly in TSX.  That is, go into the Manage Observing List, load one of the Image Planner queries from the Observing List Query set and run it.  If something goes wrong there then let me know what happens and we'll go from there.
