### ISSUE TITLE
Image Planner FOV for Preview

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#7]
I noticed the preview pics a FOV that I don't have selected in TSX.  I have multiple but only have 1 selected and used in TSX but preview pics a different one in my TSX list that isn't used.

**Comment by rrskybox** [comment]
When drawing the FOV for Preview, Image Planner reads the TSX "My Equipment.txt" file to get FOVI configuration data (which is not available through the TSX COM interface).  Unfortunately, TSX does not update this file with current configuration data, including which FOVI is "Active", until TSX is closed.  So, you have to open TSX, pick the FOVI you want to use, close TSX, then run Image Planner if you change FOVI's.  If no "Active" FOVI is found, then a default should be drawn.

The alternative would be to create a drop down list of all FOVI's in Image Planner for the user to select for each "Preview".   For me, changing FOVI's happens very rarely so I kept it simple.

**Comment by astromiester1** [comment]
Ahh... I was wondering if you knew of a filter in TSX to use for time when making an observation list. The only way I saw how to use it was to physically change the time in TSX. I was looking for a filter option for after sunset and before dawn. Couldn't find a filter option for that. Just things like transit time, Set time and rise time.  Thanks Dale

**Comment by rrskybox** [comment]
The short answer to your question is no, I don't think TSX will run a local dusk to dawn filter on an Observing List query.  TSX has a something that looks like it should do that in the Manage Observing Lists->Advanced Query->Other tab->Long Exposure Query group-> AM Twilight, PM Twilight.  But I've never been able to get it to work and the whole Long Exposure Query group is undocumented as far as I know.  I suspect that it is a TBD placeholder and has been a TBD placeholder for a long time.  However, you may have better luck than me.

That said, the Image Planner Prospect function has a built-in dusk-to-dawn filter that it applies after it makes an Observing List query (i.e. Galaxy, etc).  Dusk and dawn are set according to astronomical twilight as I recall.
