### ISSUE TITLE
Image Planner Crash When using Preview Button

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#8]
I noticed when trying to use M81 in target field with altitude and details up with chosen day once you try to select the preveiw button an unhandled exeption pops up and crashes.  It reports values was either too large or too small for an int32 number. I also notice in TSX the image for M81 fits screen but when I hit the preview button on image planner, TSX zooms into a point where image is no longer seen on TSX unless you  zoom out and image planner displays the unhandled exeption.

**Comment by rrskybox** [comment]
I haven't found a way to replicate this yet.  I suspect that it has something to do with the FOV settings.  Try this experiment for me:  open TSX, select Display->FOV Indicators, unselect all FOVI's, close TSX.  Then run ImagePlanner again with M81 and Preview.  Do you get the same behavior?  I also need to know the build for both TSX and Image Planner that you are using.

As a side note, upon launching Preview, Image Planner will zoom TSX to frame the currently active FOVI.  If the maximum zoom level for displaying the deep sky photo is smaller than the FOVI, then the photo will not display.  TSX would have to be zoomed in to display the photo.  This is normal behavior for both TSX and Image Planner.

**Comment by astromiester1** [comment]
Ok... Here are the results...

1. Using Image Planner 4.0.0.89 and Humason 4.0.0.249. TSX 64bit 10.5.0 Build 13572
2. Closed all FOVs and shut down TSX
3. Tried Preview with no FOVs and imge showed up.
4. I may of had more than one FOV selected causing the problem.

One thing I noticed... The FOV in TSX does not duplicate the one in Image planner.. Says default in image planner on image icon.

Can you match the pic in TSX FOV with your FOV?

**Comment by astromiester1** [comment]
It looks like if you change FOVs in TSX, image planner doesn't see it unless you shut down TSX and reopen. Can Image planner be setup to see more than one FOV if selected in TSX?

**Comment by rrskybox** [comment]
Based on your experiment, I suspect that the activation of multiple FOVI in TSX caused the problem, but it's probably too random to track down exactly how the failure occurs.  Your results look to be what I'd expect.  Image Planner draws the Preview FOVI based on the active TSX FOVI.  If no TSX FOVI are activated then Image Planner uses a default size.   If you enabled multiple FOVI in TSX, I'm not sure what would happen.  Just activate one at a time, if you need to change them.

A program can read in all the defined FOVI from TSX but there is no way to find out which one(s) is(are) active at any given time.  TSX saves that information to a file, but only upon closing -- that's what Image Planner reads.  So, you're kind of stuck opening and closing TSX to change the active FOVI, at least with respect to external automation like Image Planner.

**Comment by astromiester1** [comment]
Ok... Thank You...
