### ISSUE TITLE
When typing in Target Field text dissapears on every entry

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/ImagePlanner#9]
If I have NGC 1488 in field and hit return everything fine. But, when I want to change it to say 1492, the field should still keep the NGC 14XX part and just change the last too digits and hit return. Instead, any number or letter change clears out the contents making the user have to type the full target again.. Just a little thing... Thanks Dale

**Comment by rrskybox** [comment]
I removed all the auto-correct and auto-fill processing for object name entry -- MS standard as of Build 91.
